spring:
  cloud:
    nacos:
      discovery:
        server-addr: 101.33.235.76:8848
        namespace: p2p

  application:
    name: p2p-userCenter


server:
  port: 7102
  servlet:
    context-path: /p2p
