#jwtp:
#  enabled: true
#  secret: cpyjyzgz
#  expiration: 3600000
#  header: Authorization
#  userParamName: userId
#  pwdParamName: password
#  useDefaultController: true
#  skipValidUrl: /auth/login,/auth/register,/auth/logout

