spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/p2p?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: cpy50686868cpy

  redis:
    port: 6379
    host: 127.0.0.1

  cloud:
    nacos:
      discovery:
        server-addr: 101.33.235.76:8848
        namespace: p2p

  application:
    name: p2p-auth

server:
  port: 6102
  servlet:
    context-path: /p2p

